### ISSUE TITLE
[DEV] CI/CD

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/club-manager-server#16]
# Development Task 🔧
## What? ❓
More of an infrastructure task but it would be nice learning opportunity to investigate getting the server to automatically deploy new versions. EC2 and CodeDeploy are both free for small instances so I might give this a try at some point 

## Where? 🎯
AWS Developer Console

**Comment by bobheadxi** [comment]
If you want to try EC2 and Inertia instead, FYI we have a guide + automation for exactly that 😛 https://inertia.ubclaunchpad.com/#provisioning-a-remote

**Comment by DConnorFong** [comment]
This is working now!
