### ISSUE TITLE
[DEV] Investigate Gmail for Mass Emails

### ISSUE THREAD

**Issue by DConnorFong** [ubclaunchpad/club-manager-server#9]
# Development Task 🔧
## What? ❓
Please start by investigating the use of Gmail for sending out mass emails. How do we manage sending mail anonymously to people - I think that blind copy is already an effective way but We would ideally like to use the official "To" field. 

An appropriate use case is that we would like to send out 100 emails at once (probably individual if possibly). Will Google throttle this request, please investigate that too.

If we can't end up using Google for this use case, what are other alternatives... Better yet, what are cheap or free alternatives?

Report your findings under docs on the drive.

## Where? 🎯
Research
Docs

**Comment by nancywan1004** [comment]
Documenting the alternatives found here:
https://docs.google.com/document/d/1daHaOZySlhwE5IG23rd_LUKzkaIVGUlRnnLTSJQEmEs/edit

**Comment by DConnorFong** [comment]
@thomaslapadat @nancywan1004 Gmail looks like it may be a good solution. I see that there is ongoing research for MailGun too, make sure you compare notes and come to a solution before you write a lot of code

**Comment by DConnorFong** [comment]
Since we have locked in to work on GMail, I will close this.
